[package]
name = "gimme-the-3d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "fbx2gltf"
path = "src/fbx2gltf/main.rs"

[[bin]]
name = "parse"
path = "src/parse/main.rs"

[[bin]]
name = "render"
path = "src/render/main.rs"

[[bin]]
name = "render2"
path = "src/render2/main.rs"

[[bin]]
name = "server"
path = "src/server/main.rs"

[[bin]]
name = "experiment"
path = "src/experiment/main.rs"

[[bin]]
name = "convert"
path = "src/convert/main.rs"

[[bin]]
name = "parse-fbx"
path = "src/parse-fbx/main.rs"



[dependencies]
glam = "0.25.0"
gltf = "1.4.0"
anyhow = "1.0.75"
clap = "4.4.11"
tokio = { version = "1.35.0", features = ["rt", "rt-multi-thread", "macros"] }
# todo we just need headless?
three-d = { version = "0.16.3", features = ["headless", "window", "winit", "raw-window-handle"] }
three-d-asset = { version = "0.6.0", features = ["gltf", "png", "jpeg", "data-url", "reqwest"] }
nalgebra = "0.32.3"
warp = "0.3.6"
serde = { version = "1.0.193", features = ["derive"] }
log = "0.4.20"
serde_json = "1.0.108"
env_logger = "0.10.1"
tokio-stream = "0.1.14"
image = { version = "0.24.7", features = ["webp-encoder"] }
fbxcel = { version = "0.9.0", features = ["tree"] }
