port = 3030

[models]
models_base_url = 'https://jq-staging-matko.s3.eu-central-1.amazonaws.com/gltf/'
local_model_dir = 'models'
models = [
    'Beach_Towel_900x1800.glb',
    '2_p1_sweater.glb',
    '2_p1_t-shirt_Front.glb',
    '3_p1_shower-curtain_1800x2000.glb',
    'NotebookA5.glb',
    '3_p4_cushion_400x400.glb',
    '0_p1_blanket-fleece_ 1000x1000.glb',
    '0_p3_bath-towel.glb',
    '1_p1_t-shirt.glb',
    '1_p1_duvet-cover_1350x2000.glb',
    '1_p1_t-shirt-woman.glb',
    '1_p1_sweater_Front.glb',
    'PhoneCase_IPhone12.glb',
    'duvet-cover_1350x2000.glb',
    '2_p1_hoodie.glb',
    '1_p1_hoodie.glb',
]
