port = 3030

[models]
# the trailing slash is important
models_base_url = 'https://jq-staging-matko.s3.eu-central-1.amazonaws.com/gltf/'
local_model_dir = 'models'
models = [
    '0_p1_blanket-fleece_ 1000x1000.glb',
    '0_p3_bath-towel.glb',
]
